apiVersion: v2
name: contour

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number is incremented each time changes are made
# to the chart and its templates, including the app version.
version: 0.2.0

# This is the version number of the upstream Contour
# https://github.com/projectcontour/contour/releases
appVersion: v1.5.0

description: Contour is a Kubernetes ingress controller using Lyft's Envoy proxy.
home: https://projectcontour.io/
icon: https://github.com/projectcontour/contour/raw/master/contour.png
sources:
- https://github.com/projectcontour/contour
