kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
{{- if .Values.enableDefaultStorageClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
