{{- if .Values.enableMonitoring }}
# Taken from: https://grafana.com/grafana/dashboards/5342
# Linked in: https://rook.io/docs/rook/v1.3/ceph-monitoring.html#grafana-dashboards
# ceph-pools_rev3
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-pools
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "true"
data:
{{ (.Files.Glob "dashboards/ceph-pools.json").AsConfig | indent 2 }}
{{- end }}
