{{- define "secrets" }}
  apiserver.key: "{{ .Values.apiserver.apiserverKey }}"
  apiserver.crt: "{{ .Values.apiserver.apiserverCert }}"
  service-account.pub: "{{ .Values.apiserver.serviceAccountPub }}"
  ca.crt: "{{ .Values.apiserver.caCert }}"
  etcd-client-ca.crt: "{{ .Values.apiserver.etcdClientCaCert }}"
  etcd-client.crt: "{{ .Values.apiserver.etcdClientCert }}"
  etcd-client.key: "{{ .Values.apiserver.etcdClientKey }}"
  aggregation-ca.crt: "{{ .Values.apiserver.aggregationCaCert }}"
  aggregation-client.crt: "{{ .Values.apiserver.aggregationClientCert }}"
  aggregation-client.key: "{{ .Values.apiserver.aggregationClientKey }}"
{{- end -}}
# Value of "token" is composed by injecting all values into kube-apiserver-secret.yaml template and
# then calculating sha256 sum of it, so it will be different for each cluster and additionally will be
# changed every time certificate or secret template changes.
{{- define "token" -}}
{{ include "secrets" . | sha256sum }}
{{- end }}
{{- define "token-auth-file" -}}
{{ template "token" . }},nobody,nobody
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
data:
  token-auth-file: "{{ include "token-auth-file" . | b64enc }}"
{{- include "secrets" . }}
